export type WorkDataType = {
    company: string,
    date: string,
    place: string,
    title: string,
    text: string,
    stack: string,
    months?: string,
    current?: boolean,
    status?: "pending" | "completed",
    text2?: string,
    text3?: string,
    text4?: string,
    text5?: string,
}
